### ISSUE TITLE
GLOBAL: Remove orange underline from H4

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#13]
H4 doesn't need an underline

**Comment by oliverjam** [comment]
Only `h4`s or also `h5` and `h6`?

**Comment by oliverjam** [comment]
Oh I only applied it to `h2`, `h3` & `h4` 😅

**Comment by Jamchiller** [comment]
So H2 and H3 need it but H4, H5, H6 don't.

**Comment by Jamchiller** [comment]
It's just to differentiate the first two
