### ISSUE TITLE
GLOBAL: Reduce size of quote text 

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#15]
Quote text is too large, I can't seem to find the size in the code so can't say what the right size is. However, closer to [Medium's quote size](https://medium.com/sketch-app-sources/redesigning-medicspot-a-case-study-59310295bdf4) works well. Also, could it be Spectral rather than lato? 
<img width="1528" alt="Screenshot 2021-03-09 at 21 46 39" src="https://user-images.githubusercontent.com/16238581/110545783-829c8180-8125-11eb-951a-99f7caa604d6.png">

**Comment by oliverjam** [comment]
Wow lol wtf, I defo didn't do that on purpose

**Comment by oliverjam** [comment]
Ah it's cause you've got an `h1` inside the quote

```
> # “My main job satisfaction...
```

If you remove the `#` it'll be normal body copy size

**Comment by Jamchiller** [comment]
Ohhhhh okay let me have a look

**Comment by Jamchiller** [comment]
I'm having trouble pushing to the origin atm
