### ISSUE TITLE
GLOBAL: New side image component

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#18]
Since you mentioned the new custom image component, thought I'd mention this style of image too: 

<img width="761" alt="Screenshot 2021-03-09 at 22 59 45" src="https://user-images.githubusercontent.com/16238581/110550219-289eba80-812b-11eb-8f48-d6c8a5ff6cc2.png">

**Comment by oliverjam** [comment]
Does the Medium one have the text wrap under it if it's long enough? E.g. is it a proper "floating" image like in a magazine, or just two separate columns for the para and image?
