### ISSUE TITLE
GLOBAL: Buttons need hover states

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#22]
Multiple elements require hover states: 
- The primary nav items need an underline on hover, like my old site
- `View project` buttons on home page need a hover state (also, these buttons need a light stroke around them, see my designs) 
- Text links in body text need a hover state, perhaps just the underline changed to orange
- `Send now` button on the Contact page

**Comment by oliverjam** [comment]
Not really sure what kind of hover state you want for the work links. Technically the entire block is a link (including the image). since the `View project` button disappears on mobile. Currently I've just made it the same as the other links: the text in the `View project` button gets an underline when the entire thing is hovered, but maybe that's weird.

**Comment by oliverjam** [comment]
Also the orange is way too light for body link hover states.

<img width="714" alt="Screenshot 2021-03-13 at 16 04 25" src="https://user-images.githubusercontent.com/9408641/111036271-58dda600-8416-11eb-86e8-b68d8da377a4.png">

Tbh you don't _need_ these: I think most sites just have underlined links and leave it at that (the cursor changing is an indicator that you're hovering a link I guess)

**Comment by Jamchiller** [comment]
- Re: work links, ideally it was just a more white version (less transparency), I had it mocked up here in the button styles: 
https://www.figma.com/file/9zqbBlzOKDCOZp5s1Yribk/2021-Portfolio?node-id=275%3A146
It would be nice to have some sort of feedback where there's a hover, but not sure what it could be given that the whole thing is clickable, might be a bit overkill to have the whole thing change colour. 

- Re: text link underline, could you do with the blue colour in the header? Defo not essential but a nice to have, I like a bit of feedback.

**Comment by oliverjam** [comment]
Oh I didn't even look in there, was just using the screens the whole time, whoops. I can make that work I think.

I'll try the blue for body links
