### ISSUE TITLE
HOME & BLOG/CASE STUDIES - Change exact date to 'a few months ago' etc

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#23]
I really like what you've done on your site, where you don't have the exact date of the blog post, just 'this week', 'this month' etc. It would be awesome if you could apply that to the Home screen and the Blog and Work screens, but retain the exact date once someone is actually on the blog post. 

The phrases are listed below: 
`This week` D to D-7 
`This month` D-8 to D-31
`Last month` D-32 to D-63
`This year` D-63 to D-365
`More than a year ago` D-366 and below

Hope that makes sense

**Comment by oliverjam** [comment]
https://replit.com/@oliverjam/relative-time

**Comment by Jamchiller** [comment]
Nice code 👍
