### ISSUE TITLE
TAGS: Add in

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#24]
The tagging feature hasn't been added yet: 
- Tags should appear on the Blog and Work pages, but not overlap 
- If a user taps a tag, they should see all posts associated with that tag 
- If a user taps `All`, they should see all the tags (there should therefore be two versions of this page - one for `Work` and one for `Blog`

**Comment by oliverjam** [comment]
Oh I did do the all tags page but it's not linked to anywhere 🤦 
https://jaredhill-v2.netlify.app/blog/tags/
https://jaredhill-v2.netlify.app/blog/tags/cake/

I'll add the missing parts

**Comment by oliverjam** [comment]
Do you want the tags for a specific post to show up under the title? I keep meaning to add that to my site

**Comment by oliverjam** [comment]
Hm turns out non-overlapping tags is pretty tough. There's just a single pool of tags used across the site, so I'm gonna need to try and do some clever stuff to e.g. find all tags that are only used in blog posts

**Comment by oliverjam** [comment]
Also won't having tag pages for Work make it easy for people to find their way to other (not-featured) work entries?

**Comment by Jamchiller** [comment]
Quick replies: 
- The tags on the blog pages would be nice but not essential 
- Yeah but I won't be linking the Work page to anyone that I don't want to see non-featured work entries. 
- But now I think about it, I won't need tags for Work, only for Blog. So the only thing needed is removing the tag functionality from the Blog page!!
