### ISSUE TITLE
HOME: 'latest posts' seems to be showing the oldest posts

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#30]
I think it's either showing the oldest posts rather the most recent, or just showing the latest ones that were edited, rather than the latest based on the date attached to them.

**Comment by oliverjam** [comment]
Yeah I think it defaults to oldest first, just need to reverse it

**Comment by oliverjam** [comment]
Oh whoops this was fixed in https://github.com/oliverjam/jaredhill-v2/commit/771d115f34edf33c55e8db5f3c63fcbd48435383, forgot to link the commit
