### ISSUE TITLE
Safari and Firefox adjustments

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#41]
A few bugs on both to look at - low prio

**Comment by oliverjam** [comment]
Need to use grid instead of flexbox even for horizontal stacks, as `gap` isn't supported in Safari yet.

Look into wtf is going on with text-decoration lol

**Comment by oliverjam** [comment]
Oh FFS Safari
<img width="1039" alt="Screenshot 2021-05-05 at 19 38 53" src="https://user-images.githubusercontent.com/9408641/117192425-9be64500-add9-11eb-8656-a01ff3caebe9.png">

**Comment by Jamchiller** [comment]
Haha wait isn't that a good thing?

**Comment by oliverjam** [comment]
Yeah but it's just too late for this site atm, since Safari 14.1 won't be used by most actual people for a bit (since unlike Chrome Safari updates are tied to entire system updates. Most people put off macOS updates for a while 🙃)

So I'll have to do a hacky workaround anyway

**Comment by Jamchiller** [comment]
I didn't realise that but noticed it said '14.1 for Big Sur'. So dumb. We only _just_ got updated to Catalina on our work laptops, will be at least another year before we get Big Sur...

**Comment by oliverjam** [comment]
Jeez you don't get to choose when to upgrade? I'm curious: what version of Safari do you have on Catalina?

**Comment by Jamchiller** [comment]
Nope, it's so annoying, I really want Big Sur. They have full control over our Macs, it's actually quite impressive. 

It's 13.1.3
