### ISSUE TITLE
HOME: On hover over 'My work' containers, make little chevrons move back and forth

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#45]
ANIMATION BABY!!!!!!

**Comment by Jamchiller** [comment]
Low prio

**Comment by oliverjam** [comment]
Is that not what they already do? Or do you mean like continuously animate while you're hovering them?

**Comment by Jamchiller** [comment]
Yes exactly, continuously animate back and forth

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oliverjam** [comment]
Oh fixed in https://github.com/oliverjam/jaredhill-v2/commit/91a1805ced43d07cdff4ca1df0c88d7c73dea555
