### ISSUE TITLE
GLOBAL - Footer copy same line height, size as body copy

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#5]
It seems to have a different line height

**Comment by oliverjam** [comment]
Yeah I gave it a tighter leading cause it's like a single standalone line of text. Can space it back out though.

## Before

<img width="1680" alt="Screenshot 2021-03-09 at 23 19 31" src="https://user-images.githubusercontent.com/9408641/110551710-efb41500-812d-11eb-9836-be626c09d691.png">

## After

<img width="1680" alt="Screenshot 2021-03-09 at 23 19 24" src="https://user-images.githubusercontent.com/9408641/110551718-f3479c00-812d-11eb-8299-b6caca8f685d.png">

**Comment by oliverjam** [comment]
@Jamchiller you ok with the after there?

**Comment by Jamchiller** [comment]
I missed this! yes that's great

**Comment by Jamchiller** [comment]
As long as it's just the body copy style, then if I play around with the body copy itself, this will change too. Which is what I want, since when you implement the wider container, we might need to play around with text size.
