### ISSUE TITLE
About page - slight structural changes

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#50]
I've made some structural changes to the About page, pushing the text area to the left and adding the image in the spare space as I wasn't a huge fan of the inset image in the end. This is low priority though. See the figma for details: 

https://www.figma.com/file/9zqbBlzOKDCOZp5s1Yribk/2021-Portfolio?node-id=607%3A0

**Comment by oliverjam** [comment]
Cool. To future-proof it a bit I can probs make a `{% columns 2 %}` shortcode that lets you manually divide markdown content into columns so you have more control.

**Comment by Jamchiller** [comment]
That would be awesome. Would also set us up for some more enhancements in the future...
![Screenshot 2021-03-24 at 13 52 51](https://user-images.githubusercontent.com/16238581/112321809-4847ee00-8ca8-11eb-955b-080672dda658.png)

**Comment by oliverjam** [comment]
How is this?

<img width="1669" alt="Screenshot 2021-05-07 at 15 09 05" src="https://user-images.githubusercontent.com/9408641/117466413-95c3a600-af4a-11eb-8c45-e6e2219cf176.png">
