### ISSUE TITLE
BLOG POST: Add quote text styling

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#56]
Quote text to be a lighter grey and smaller. See this page for example: 

https://www.figma.com/file/9zqbBlzOKDCOZp5s1Yribk/2021-Portfolio?node-id=233%3A737

**Comment by oliverjam** [comment]
Whoops wrong one

**Comment by oliverjam** [comment]
The design shows the quotation text as larger than the body, not smaller? 28px vs 24px on Figma

**Comment by oliverjam** [comment]
<img width="1239" alt="Screenshot 2021-05-07 at 14 23 30" src="https://user-images.githubusercontent.com/9408641/117456148-ce11b700-af3f-11eb-8bf9-ad6739fc9478.png">

How's this?

**Comment by Jamchiller** [comment]
Lol, why did I say smaller. Larger is what I meant. That looks nice!
