### ISSUE TITLE
CONTACT PAGE: Placeholder text is smaller than input text

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#58]
The placeholder text is small, but when you type into an input the text is body text size. It's a little jarring. Can you bring the placeholder text up to body text size too?

**Comment by oliverjam** [comment]
Oh weird, looks like placeholder text doesn't inherit the same font-size as the input :/

**Comment by Jamchiller** [comment]
Weird one huh

**Comment by oliverjam** [comment]
Fixed in https://github.com/oliverjam/jaredhill-v2/commit/8b21ae6dfedc7249b7de88d4dca44f1b5513493a

**Comment by Jamchiller** [comment]
niiiice! So spacious I love it
