### ISSUE TITLE
HOME PAGE - Remove pay/pause button on hover

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#6]
There is a play/pause button that appears on hover in the quotes section, is it possible to remove?

**Comment by oliverjam** [comment]
Yup can easily get rid, but then there's no way to stop the animation. It's _generally_ a good idea to let users opt out of motion, especially when it's moving text they might be trying to read.

The animation does respect the `prefers-reduced-motion` preference (e.g. you can choose "Reduced motion" in Mac/iPhone settings), but not all devices support this and not all users know about it.

**Comment by Jamchiller** [comment]
Love it, that's a good enough reason for me!
