### ISSUE TITLE
GLOBAL: Custom image component

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#66]
Thought I'd put this separate as you've been mentioning it a bit but seems like a bigger separate job to some of the other tickets.

**Comment by Jamchiller** [comment]
To add something else to this, just to make it even harder - it would be nice to have an 'expand' option on this, so that images could be viewed in full. Check out the images on medium: 
https://jamchiller.medium.com/standard-bank-a-case-study-afc14f2eebf7

This portofolio does 'zoom in place' images which is pretty cool too but probably worse for viewing images in detail: 
https://joelcalifa.com/work/digitalocean-onboarding/

**Comment by oliverjam** [comment]
Can do that really simply by making them link to the full size image in a new tab.

Then maybe enhance at some point with a little JS so it does a lightbox overlay type thing on the same page

**Comment by Jamchiller** [comment]
Perfect. Sounds like a good plan

**Comment by oliverjam** [comment]
Ok I made a hacky one that doesn't really need any JS 😅 
https://codepen.io/oliverjam/full/mdWypqm

**Comment by Jamchiller** [comment]
You can truly do anything to avoid JS! 😂 

Could this have a pointer on hover? If so, that's a really good workaround

**Comment by oliverjam** [comment]
Yeah definitely, I know you love that finger

**Comment by Jamchiller** [comment]
Genuinely obsessed with it
