### ISSUE TITLE
GLOBAL: Video embeds

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#67]
I need to be able to embed videos, is there an easy way of doing this with markdown?

**Comment by oliverjam** [comment]
Ye-es. Are these vids hosted on other platforms like YouTube? Or your own vids you want to upload directly to this site?

**Comment by Jamchiller** [comment]
Just on youtube. See my usability tips article for an example of the issues: 
https://jaredhill.co/blog/eight-bodacious-tips/

Here it is on medium:
https://bootcamp.uxdesign.cc/eight-totally-bodacious-usability-testing-tips-expressed-as-80s-hit-singles-cc04a1c644bc

**Comment by oliverjam** [comment]
Cool.

This is just a reminder for myself when I implement this: https://github.com/paulirish/lite-youtube-embed/
