### ISSUE TITLE
GENERAL: Make it 'pop' more

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#74]
Not popping enough (could be the logo?). Please prioritise this one Olly.

**Comment by Jamchiller** [comment]
Btw, this is a fairly quick task - I expect it should only take you an hour or two.

**Comment by oliverjam** [comment]
boom, 2 minutes

https://user-images.githubusercontent.com/9408641/151822217-d91133d0-d82e-4d07-9183-ac231b3ea5f9.mp4

**Comment by Jamchiller** [comment]
This is good, but I was thinking more something like pelicans flying across the screen........... my friend's son is also a developer and said this should be pretty easy.............
