### ISSUE TITLE
Add something for ---

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#75]
When I type --- in markdown I want a separator

**Comment by oliverjam** [comment]
Just a regular line or something fancier?

**Comment by Jamchiller** [comment]
Looking for something ideally similar to the Medium one (I'm a shameless plagiarist) 

<img width="760" alt="Screenshot 2022-02-06 at 13 13 12" src="https://user-images.githubusercontent.com/16238581/152682601-1388c496-c301-486b-afe6-811a8258a433.png">
