### ISSUE TITLE
Just one final spacing issue

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#78]
I will talk to you about this separately - essentially regarding the spacing below the callout text. It looks good when there's a H1 below is but not when there's body text, might need a tiny bit of tweaking! But only a problem on desktop so gonna be fun to tweak.

<img width="1258" alt="Screenshot 2022-02-06 at 14 12 28" src="https://user-images.githubusercontent.com/16238581/152684951-7ebd4bf9-85ff-4aea-98c7-1f17c26ce7cc.png">

**Comment by oliverjam** [comment]
@Jamchiller what exactly do you wanna change here?

**Comment by Jamchiller** [comment]
I say ignore this one. I had a play around and couldn't find a good middle ground between allowing spacing when there's body text afterwards and when there's H1. It's a minor minor problem so let's just leave it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jamchiller** [comment]
@oliverjam you solved this somehow in the update!>!?!
