### ISSUE TITLE
GLOBAL - Another large body copy size

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#8]
I'd like to be able to have some introductory copy at the beginning of blog posts that is bigger than the rest, something like 1.7em / 1.8em. Not sure how to do this in the code editor, does this need to be added as a style? 

See this example: 
https://www.figma.com/file/9zqbBlzOKDCOZp5s1Yribk/2021-Portfolio?node-id=233%3A737

**Comment by oliverjam** [comment]
So each page should really have a "meta description" anyway. This is a short-ish description of the page content, used for SEO and stuff (e.g. it shows up in Google search results).

So ideally each page needs not only a title, date etc but also a description in its structured data (at the top). If the introductory copy is always in the same place then I can re-use this description for that too.

So you'd write it like:

```markdown
---
title: Test post
date: 2021-03-09
description: This post is about testing
---

The rest of the blog post
```

And the output HTML would be like:

```html
<h1>Test post</h1>
<span>9 Mar 2021</span>

<main>
  <p class="big-text">This post is about testing</p>
  <p>The rest of the blog post</p>
</main>
```

**Comment by Jamchiller** [comment]
Yeah that would work! It's always at the very beginning of the post or page. I won't always use it but that's fine, can just not fill in the description.
