### ISSUE TITLE
Twitter embeds

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#80]
Essentially what it says on the tin... would this be a quick js addition or something more? I noticed this as I have [a Tweet linked]([url](https://jaredhill.co/blog/eight-bodacious-tips/#2-the-magic-number)) in this post. 

Worst case scenario I'll screenshot the tweet. Lemme know

**Comment by oliverjam** [comment]
Probably not too much work. Ideally I'll find a "lite" version of the official Twitter embed (same as the YouTube one)

**Comment by oliverjam** [comment]
Hm the official embed is horrible. Maybe I'll make my own - a tweet is basically just a fancy looking blockquote tbh

**Comment by Jamchiller** [comment]
Ahh okay. No need to make your own though (unless you have time). 

I can totally just screenshot - probably better in some ways too as tweets can get taken down.

**Comment by oliverjam** [comment]
Just did a little research. We have 3 options:
1. Just use a screenshot
2. Just paste the tweet's official embed code into the Markdown (i.e. what it gives you when you click "Embed tweet")
3. Sign up for a Twitter developer API account, build a custom thing, it's a surprising amount of work

Downsides to 2) are that it's a bunch of JS loaded from Twitter's domain, that is blocked by a lot of ad blockers (my Edge browser was blocking it cause of a built-in anti-tracking feature I had turned on).

**Comment by Jamchiller** [comment]
Just used the embed code, that actually worked really well. I feel like I actually prefer screenshots so might just use them in future for both Medium and personal site posts. But not bad at all! Thanks man
