### ISSUE TITLE
Maintain aspect ratio of images when expanded on

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#85]
I've been adding the new image feature you made (where you can click on and expand an image) and it seems that for images that are similar height and width, sometimes it can cut off the top and bottom of the image in order to expand it to full width. 

Some good examples are the images in this post - https://jaredhill.co/blog/thanks-for-the-memories/

Not sure how easy/hard it would be to limit the max-width of the 'zoomed' image so that the top and bottom of the image aren't cut off, very low priority but thought I'd capture it here anyway.

**Comment by oliverjam** [comment]
Hmm I think the simplest solution would be to not force the images to be 100% width. This would allow them to display at their native size and aspect ratio.

The only downside is if your images aren't that big then they won't get any bigger when clicked on 😅. See this [example page](https://codepen.io/oliverjam/full/mdWypqm). The first one is 2000x2000 pixels so when you click it it fills the space. The second one is only 400x400 so doesn't change size when clicked.

**Comment by Jamchiller** [comment]
Nah that's actually a perfect solution. Would prefer them not to get bigger than their actual size anyway, better to be small than big and blurry!
