### ISSUE TITLE
WORK - Create 'work' page

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#9]
I think you might've done this but I couldn't find it at https://jaredhill-v2.netlify.app/work

Should be a list of case studies.

As per this convo: 
<img width="689" alt="Screenshot 2021-03-05 at 13 25 54" src="https://user-images.githubusercontent.com/16238581/110121529-68297780-7db6-11eb-97a2-8aa79ebf7db9.png">

**Comment by oliverjam** [comment]
Do you want Work in the global nav as well? Home, About, Blog, Work, Contact?

**Comment by Jamchiller** [comment]
nope, unable to navigate to. Ideally I'd like to make sure google doesn't index that page too as it'll have sensitive client info on it. So will need to add that robots.txt thing or whatever the equivalent is now

**Comment by oliverjam** [comment]
Okay so only the ones with `featured: true` that appear on the home page will be visible to anyone?

**Comment by Jamchiller** [comment]
Yes, exactly. There will be three 'whitelabelled' ones accessible from the home page, and then I'll have other non whitelabelled ones published but only accessible from the `work` page and if I send the URL.

**Comment by Jamchiller** [comment]
So people will only really be able to see 3 case studies at a time

**Comment by Jamchiller** [comment]
It's not exactly the most locked down method but as long as I 'attempt' to not show the private ones. 

(Also sorry for all these separate messages)

**Comment by oliverjam** [comment]
- [x] Remove /work from nav
- [x] Hide /work in ~~robots.txt~~ noindex header
- [x] Use blog post format for work post list

**Comment by oliverjam** [comment]
@Jamchiller I think we can close this finally?

**Comment by Jamchiller** [comment]
Yes! Closed!
